---
name: "CI"

on:
  - "pull_request"

concurrency:
  group: "${{ github.ref_name }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: "Install dependencies"
        run: |
          pip install --upgrade pip "setuptools<72.0.0"
          pip install -r requirements-lint.txt
      - name: "Run linter"
        run: |
          make lint

  test:
    needs:
      - "lint"
    uses: "./.github/workflows/test.yml"

  sanity:
    runs-on: "ubuntu-latest"
    needs:
      - "lint"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: "Install dependencies"
        run: |
          make test-setup
      - name: "Run sanity check"
        run: |
          make SANITY_OPTS="--local" sanity

  ready-to-ship:
    # This is a dummy dependent task to have a single entry for the branch protection rules.
    runs-on:  "ubuntu-latest"
    needs:
      - "lint"
      - "test"
      - "sanity"
    steps:
      - name: "All set"
        run: |
          echo "CI says: Looks good!"
...
