---
name: "Test"

on:
  - "workflow_call"

env:
  COLORTERM: "yes"
  TERM: "xterm-256color"
  PYTEST_ADDOPTS: "--color=yes"
  CONTAINER_RUNTIME: "docker"

jobs:
  test:
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.9"
            ansible: "stable-2.15"
            image_tag: "latest"
          - python: "3.10"
            ansible: "stable-2.16"
            lower_bounds: true
          - python: "3.11"
            ansible: "stable-2.17"
          - python: "3.12"
            ansible: "devel"
            image_tag: "nightly"
            lower_bounds: true
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('**/*requirements*.txt', '**/*constraints*.lock', '**/setup.py', '**/pyproject.toml') }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python }}"
      - name: "Install dependencies"
        run: |
          if [ "${{matrix.lower_bounds}}" ]
          then
            make ANSIBLE_VERSION=${{ matrix.ansible }} test-setup-lower-bounds
          else
            make ANSIBLE_VERSION=${{ matrix.ansible }} test-setup
          fi
      - name: "Run basic tests"
        run: |
          make test
      - name: "Run live tests"
        run: |
          IMAGE_TAG=${{ matrix.image_tag }} tests/run_container.sh make livetest
        if: "${{ matrix.image_tag }}"
...
